### PR TITLE
include atracker event routing in upgrade test

### PR DESCRIPTION
**Pull request by Aayush-Abhyarthi**
### Description

https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/issues/272

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by Aayush-Abhyarthi** [comment]
As per the comment https://github.ibm.com/GoldenEye/issues/issues/4525#issuecomment-56117078 I reduced the number of tests creating routes, but this fails the upgrade test. Any action is needed here now?

**Comment by ocofaigh** [comment]
Adding codeowners for review

**Comment by iamar7** [comment]
Closing this PR as this work is being continued in this PR https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/pull/508

**Pull request closed without merging**
