### PR TITLE
fix : target variable mark sensitive

### PR DESCRIPTION
**Pull request by Khuzaima05**
### Description

Activity tracker target variables should be marked as sensitive

Git issue: https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/issues/270
#### Changes that affect the core Terraform module or submodules
- [x] Bug fix
- [ ] New feature
- [ ] Dependency update

#### Changes that don't affect the core Terraform module or submodules
- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other

#### Release required?
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

mark the target variable sensitive

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

### CODE REVIEW

**Comment by ocofaigh** [comment]
Looks like when you mark is as sensitive it breaks the code. Suggest talking with @Aashiq-J to see how we can refactor the code here

```
│ Error: Invalid for_each argument
│ 
│   on ../../modules/activity_tracker/main.tf line 55, in resource "ibm_atracker_target" "atracker_cos_targets":
│   55:   for_each = { for target in var.cos_targets : target.target_name => target }
│     ├────────────────
│     │ var.cos_targets has a sensitive value
│ 
│ Sensitive values, or values derived from sensitive values, cannot be used
│ as for_each arguments. If used, the sensitive value could be exposed as a
│ resource instance key.
```

**Review by shemau — CHANGES_REQUESTED** [review]
The root module has the same issue and other sensitive targets would benefit from the same treatment.

**Comment by Khuzaima05** [comment]
> The root module has the same issue and other sensitive targets would benefit from the same treatment.

resolved

**Review by shemau — DISMISSED** [review]
Looks good now.

**Review by shemau — APPROVED** [review]
Still looks good to go

**Pull request merged**
