### PR TITLE
fix: add 180 to cloud logs retention period

### PR DESCRIPTION
**Pull request by kierramarie**
### Description

Added 180 to valid cloud logs retention variable validations.

Git Issue: https://github.com/terraform-ibm-modules/terraform-ibm-observability-da/issues/173

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by iamar7** [comment]
@kierramarie can you resolve the pre-commit issue in this PR?

**Comment by kierramarie** [comment]
> @kierramarie can you resolve the pre-commit issue in this PR?

@iamar7  It is failing on detect secrets in the READMEs. There are no secrets and I am unable to add the allowlist comment because the precommit removes it. How do I fix this?

**Comment by iamar7** [comment]
> > @kierramarie can you resolve the pre-commit issue in this PR?
> 
> @iamar7 It is failing on detect secrets in the READMEs. There are no secrets and I am unable to add the allowlist comment because the precommit removes it. How do I fix this?

Let me check what to do.

**Review by iamar7 — APPROVED** [review]
LGTM

**Comment by kierramarie** [comment]
180 is currently not a valid input for cloud logs retention period

**Pull request closed without merging**
