### PR TITLE
add support to enable platform logs with a boolean for cloud logs + cleanup

### PR DESCRIPTION
**Pull request by ocofaigh**
### Description

- Added new variable to the cloud logs module - `enable_platform_logs` which will now automatically create a tenant in the region that the cloud logs instance is provisioned. This variable already existed at the root module, but was only used by logdna.
- Added deprecated warnings to all logdna, and AT variables and outputs. I also made it so the module no longer deploys these by default.
- Cleanup to both examples (meaning upgrade test needs to be skipped)
- Cleanup to all readmes

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by ocofaigh** [comment]
The upgrade test is failing with `Error: Cannot read the remote archive resource` because I removed the apikey from the logdna provider config since we no longer provision logdna as its deprecated. 
Skipping upgrade test..

**Review by iamar7 — APPROVED** [review]
LGTM

**Pull request merged**
