### PR TITLE
fix: fix cycle error

### PR DESCRIPTION
**Pull request by ocofaigh**
### Description

In https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/pull/576 I added some logic to the outputs in the root level module for log analysis, however there was a knock on affect which was causing a cycle error:

`Cycle: provider[\"registry.terraform.io/logdna/logdna\"].ld, module.observability_instances.module.log_analysis.logdna_archive.archive_config, module.observability_instances.module.log_analysis (close), module.observability_instances.output.log_analysis_resource_key (expand)`

I was able to reproduce in the examples, and have updated the conditional logic in the outputs to fix the issue

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by iamar7 — APPROVED** [review]

**Comment by ocofaigh** [comment]
The upgrade test is failing on below since I updated the test to use a prefix in the EN integration name (as it was giving a name clash error). This is an expected update and skipping upgrade test will have no impact on the module itself.
```
2024-09-30T09:19:36.3977504Z         	Messages:   	Resource(s) identified to be updated 
2024-09-30T09:19:36.3978207Z         	            	Name: en_integration
2024-09-30T09:19:36.3979337Z         	            	Address: module.observability_instances.module.cloud_logs[0].ibm_logs_outgoing_webhook.en_integration["0"]
2024-09-30T09:19:36.3980471Z         	            	Actions: [update]
2024-09-30T09:19:36.3981015Z         	            	DIFF:
2024-09-30T09:19:36.3981487Z         	            	  Before: 
2024-09-30T09:19:36.3982204Z         	            		{"name":"cloud-logs-eu-de-en-integration-0"}
2024-09-30T09:19:36.3982875Z         	            	  After: 
2024-09-30T09:19:36.3983523Z         	            		{"name":"obs-upg-nmqlcy-en"}
```

**Review by iamar7 — APPROVED** [review]

**Pull request merged**
